server:
  port: 10001

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:10000/eureka/

spring:
  application:
    name: boss-bes-user-permission-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_basedata_center?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.bosssoft.bes.userpermission.pojo.dto
  mapper-locations: classpath*:mapper/*.xml

#通用mapper配置
mapper:
  #公用接口类路径
  mappers: tk.mybatis.mapper.common.Mapper
  identity: MYSQL
redis:
  host: 127.0.0.1
  port: 6379
  password:
  pool:
    max-active: 8
    max-wait: 1
    max-idle: 8
    min-idle: 0
  timeout: 0
#feign:
#  hystrix:
#    enabled: true